name: first pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    run-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3

    



  

        

      
  

